# Aggregation and Grouping exercises

In [1]:
import numpy as np
import pandas as pd

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

First let's load some data on NBA players:

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/sivabalanb/Data-Analysis-with-Pandas-and-Python/master/nba.csv')
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

Using this data answer the following.

* What is the average salary per team?

In [3]:
# average salary per team
df.groupby('Team')['Salary'].mean().sort_values()

Team
Philadelphia 76ers        2.213778e+06
Portland Trail Blazers    3.220121e+06
Brooklyn Nets             3.501898e+06
Boston Celtics            4.181505e+06
Utah Jazz                 4.204006e+06
Phoenix Suns              4.229676e+06
Denver Nuggets            4.294424e+06
Orlando Magic             4.297248e+06
Milwaukee Bucks           4.350220e+06
New Orleans Pelicans      4.355304e+06
Indiana Pacers            4.450122e+06
Detroit Pistons           4.477884e+06
New York Knicks           4.581494e+06
Minnesota Timberwolves    4.593054e+06
Toronto Raptors           4.741174e+06
Dallas Mavericks          4.746582e+06
Sacramento Kings          4.778911e+06
Los Angeles Lakers        4.784695e+06
Atlanta Hawks             4.860197e+06
Houston Rockets           5.018868e+06
Washington Wizards        5.088576e+06
Charlotte Hornets         5.222728e+06
Memphis Grizzlies         5.467920e+06
San Antonio Spurs         5.629516e+06
Chicago Bulls             5.785559e+06
Golden State Warriors     5.924600e+06
Oklahoma City Thunder     6.251020e+06
Los Angeles Clippers      6.323643e+06
Miami Heat                6.347359e+06
Cleveland Cavaliers       7.642049e+06
Name: Salary, dtype: float64

* What is the average salary per team and position? In other words, compute how much do centers, power forwards etc. make in each team.

In [4]:
# average salary per team / position
df.groupby(['Team', 'Position'])['Salary'].mean().unstack()

Position,C,PF,PG,SF,SG
Team,,,,,
Atlanta Hawks,7.585417e+06,5.988067e+06,4.881700e+06,3.000000e+06,2.607758e+06
Boston Celtics,2.450465e+06,6.056987e+06,4.974652e+06,6.796117e+06,2.107997e+06
Brooklyn Nets,1.031814e+07,3.576205e+06,2.915759e+06,NaN,1.473351e+06
Charlotte Hornets,6.772240e+06,4.685770e+06,4.776152e+06,6.331404e+06,4.661406e+06
Chicago Bulls,1.042438e+07,3.361007e+06,1.117153e+07,1.958160e+06,5.717549e+06
Cleveland Cavaliers,6.828957e+06,1.394101e+07,6.551592e+06,1.195889e+07,3.761809e+06
Dallas Mavericks,2.332019e+06,3.052835e+06,4.418183e+06,8.231051e+06,8.928250e+06
Denver Nuggets,1.617240e+06,7.024978e+06,3.482413e+06,9.327590e+06,9.300817e+05
Detroit Pistons,4.090697e+06,4.000000e+06,4.260003e+06,5.173600e+06,4.580880e+06
Golden State Warriors,6.541249e+06,7.275312e+06,8.457256e+06,3.766367e+06,6.316092e+06
Houston Rockets,1.165332e+07,1.755114e+06,3.343543e+06,3.381986e+06,7.030721e+06
Indiana Pacers,4.000000e+06,2.064961e+06,4.054692e+06,7.624404e+06,5.700000e+06
Los Angeles Clippers,1.039480e+07,6.655482e+06,8.509072e+06,3.662924e+06,4.639893e+06
Los Angeles Lakers,5.806208e+06,2.253022e+06,2.157757e+06,7.966611e+06,7.000000e+06
Memphis Grizzlies,1.968800e+07,4.435691e+06,5.144664e+06,4.581313e+06,3.550386e+06
Miami Heat,9.813480e+05,7.884668e+06,1.478300e+07,3.460626e+06,7.123384e+06
Milwaukee Bucks,9.258397e+06,2.980240e+06,3.415350e+06,1.034762e+06,6.345079e+06
Minnesota Timberwolves,6.426013e+06,4.796280e+06,5.376813e+06,1.384565e+06,5.758680e+06
New Orleans Pelicans,4.850122e+06,6.140243e+06,3.910588e+06,1.661921e+06,5.497929e+06
New York Knicks,7.732000e+06,3.379299e+06,4.487586e+06,6.346947e+06,2.489935e+06
Oklahoma City Thunder,6.303143e+06,5.821013e+06,9.382869e+06,8.599621e+06,3.207058e+06
Orlando Magic,6.098638e+06,4.688068e+06,4.286164e+06,8.450590e+05,3.740735e+06
Philadelphia 76ers,4.604820e+06,2.889266e+06,1.141104e+06,9.225295e+05,1.908358e+06
Phoenix Suns,5.630172e+06,3.267500e+06,7.000750e+06,2.582424e+06,1.423116e+06
Portland Trail Blazers,4.470774e+06,2.079564e+06,3.545614e+06,5.468477e+06,2.124524e+06
Sacramento Kings,8.983410e+06,6.850760e+05,7.256780e+06,4.417456e+06,2.794976e+06
San Antonio Spurs,3.724319e+06,1.059409e+07,5.755732e+06,8.775190e+06,3.384923e+06
Toronto Raptors,3.105494e+06,2.978463e+06,6.836453e+06,6.225972e+06,5.350000e+06
Utah Jazz,1.674385e+06,6.338267e+06,2.442323e+06,6.146973e+06,5.405962e+06
Washington Wizards,8.163476e+06,5.650000e+06,9.011208e+06,2.789700e+06,2.839248e+06

* Who is the oldest player in each team?  Who is the oldest player in the Boston Celtics?

In [5]:
idx = df.groupby('Team')['Age'].idxmax()
new_df = df.loc[idx].sort_values(by = "Age", ascending = False)
new_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,8500000.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
256,Jason Terry,Houston Rockets,31.0,SG,38.0,6-2,185.0,Arizona,947276.0
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
236,Dirk Nowitzki,Dallas Mavericks,41.0,PF,37.0,7-0,245.0,NaN,8333334.0
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
343,Udonis Haslem,Miami Heat,40.0,PF,36.0,6-8,235.0,Florida,2854940.0
72,Luis Scola,Toronto Raptors,4.0,PF,36.0,6-9,240.0,NaN,2900000.0
139,Caron Butler,Sacramento Kings,31.0,SF,36.0,6-7,228.0,Connecticut,1449187.0
392,Mike Miller,Denver Nuggets,3.0,SG,36.0,6-8,218.0,Florida,947276.0
183,Steve Blake,Detroit Pistons,22.0,PG,36.0,6-3,172.0,Maryland,2170465.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
170,Richard Jefferson,Cleveland Cavaliers,24.0,SF,35.0,6-7,233.0,Arizona,947276.0
154,Mike Dunleavy,Chicago Bulls,34.0,SG,35.0,6-9,230.0,Duke,4500000.0
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,NaN,7402812.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
76,Leandro Barbosa,Golden State Warriors,19.0,SG,33.0,6-3,194.0,NaN,2500000.0
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,NaN,13000000.0
221,Steve Novak,Milwaukee Bucks,6.0,SF,32.0,6-10,225.0,Marquette,295327.0
367,C.J. Watson,Orlando Magic,32.0,PG,32.0,6-2,175.0,Tennessee,5000000.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
292,Kendrick Perkins,New Orleans Pelicans,5.0,C,31.0,6-10,270.0,NaN,947276.0
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0
198,Monta Ellis,Indiana Pacers,11.0,SG,30.0,6-3,185.0,NaN,10300000.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0

In [6]:
df.loc[df['Team']=="Boston Celtics"].sort_values(by = "Age", ascending = False).head(1)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

* Which college has produced the largest number of players?  You can use the `count` method as the aggregation method in your groupby operation.

In [7]:
# college that produced the largest number of players
df.groupby('College')['Name'].count().sort_values(ascending=False).head(1)

College
Kentucky    22
Name: Name, dtype: int64

In [8]:
df.groupby('College').agg(player_count = ('Name', 'count')).sort_values(by='player_count', ascending=False).head(1)

          player_count
College
Kentucky            22

* For each player, indicate whether he is earning more than the average for his team or not.  Here you can use the `apply` method.

In [13]:
def above_avg(group):
    return group['Salary'] > group['Salary'].mean()


result = df.groupby('Team', group_keys=False).apply(above_avg)
df["Above Average Salary"] = result
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Above Average Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,True
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,True
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,False
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,False
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,True
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,False
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,False
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,False
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,False
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* Choose one of the above exercises and do it without the ``groupby`` functionality.

In [ ]:
# see, we can do it without groupby!  (but a bit more work?)
#I'm doing average salary per team. Said I could copy and paste Thanks! 
df.loc[df['Team']=="Boston Celtics"].sort_values(by = "Age", ascending = False).head(1)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Above Average Salary
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,True